name: Trigger auto deployment for container-app-3obglz3n5zjhw

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-3obglz3n5zjhw-AutoDeployTrigger-82c05008-4758-4147-92b7-20fa4c5ca4f4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3OBGLZ3N5ZJHW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3OBGLZ3N5ZJHW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3OBGLZ3N5ZJHW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3OBGLZ3N5ZJHW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3OBGLZ3N5ZJHW_REGISTRY_PASSWORD }}
          containerAppName: container-app-3obglz3n5zjhw
          resourceGroup: appspacestododemoa545
          imageToBuild: default/container-app-3obglz3n5zjhw:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


